using Application.Commands.RegistrationCommands;
using Application.DTO.EmailDto;
using Application.DTO.RegistrationDto;
using Application.Email;
using Application.Interfaces;
using Application.Validators.RegistrationValidators;
using EfDataAccess;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;

namespace EfCommands.EfRegistrationCommands
{
    public class EfRegisterBusinessUserCommand : EfBaseCommand, IRegisterBusinessUserCommand
    {
        private readonly RegisterBusinessUserValidator _validator;
        private readonly IEmailSender _sender;

        public EfRegisterBusinessUserCommand(EfContext context, 
            RegisterBusinessUserValidator validator, IEmailSender sender) 
            : base(context)
        {
            _sender = sender;
            _validator = validator;
        }

        public int Id => 85;

        public string Name => "Register Business User Command Using EF";

        public IEnumerable<Role> Roles => new List<Role> { Role.Anonymus };

        public void Execute(RegisterBusinessUserDto request)
        {
            _validator.ValidateAndThrow(request);

            var theatre = new Domain.Theatre
            {
                TheatreName = request.Theatre,
                Location = request.Location,
                Longitude = request.Longitude,
                Latitude = request.Latitude
            };

            Context.Theatres.Add(theatre);

            byte[] passwordHash, passwordKey;

            using (var hmac = new HMACSHA512())
            {
                //random key generated by Hash-Based Message Authentication Code (hmac)
                passwordKey = hmac.Key;
                passwordHash = hmac.ComputeHash(System.Text.Encoding.UTF8.GetBytes(request.Password));
            }

            var user = new Domain.User
            {
                FirstName = request.FirstName,
                LastName = request.LastName,
                Email = request.Username,
                RoleId = 2,
                Password = passwordHash,
                PasswordKey = passwordKey,
                Status = Domain.User.StatusType.Pending,
                Theatre = theatre
            };

            Context.Users.Add(user);

            Context.SaveChanges();

            _sender.Send(new SendEmailDto
            {
                Content = "<h1>Thank you for your application!</h1>" +
               "<h2> We'll check it soon.</h2>",
                SendTo = request.Username,
                Subject = "Application Successful"
            });

        }
    }
}
